version: '3'
services:

  #FAST API Service
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    env_file: .env
    command: bash -c "cd app && alembic upgrade head && cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network


  #Postgres Service
  db:
    image: postgres:12.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
      - POSTGRES_USER=fast_movie_user
      - POSTGRES_DB=fast_movie
      - POSTGRES_PASSWORD=fast_movie_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@fastmovie.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - db


#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local